/*
	this file is auto generated by toolchain_check.sh Version: 0.1
		1 	// aosp: prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8 
		2 	// aosp: prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 
*/
#define SUBVER_RTKBT_TOOLCHAIN (3)
